# Generated by Django 3.1.2 on 2020-11-17 17:38

from django.db import migrations, IntegrityError, transaction
from django.contrib.auth.models import Group


def group_creator(apps, schema_editor):
    Group.objects.create(name='Customers')
    managers = Group.objects.create(name='Managers')
    admin = Group.objects.create(name='Admin')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201201_0119'),
    ]

    operations = [
        migrations.RunPython(group_creator),
    ]
